### ISSUE TITLE
Manually configured tag isn't prefixed in release name

### ISSUE THREAD

**Issue by BasMatthee** [leviy/release-tool#41]
When I choose to release a manually chosen version (Let's say 0.0.5, so `./release-tool.phar release 0.0.5`), the tag gets properly prefixed with the configured prefix (`v0.0.5`) but after pushing the tag to the repository, the releases-page (github) says the name of the release is `0.0.5` instead of the `v0.0.5` as would be done when using the yes/no questions-path.

**TLDR**
*Manually supply tag*
Release > Tag is prefixed > Release name on GitHub is **not** prefixed.
*Calculate the tag*
Release > Tag is prefixed > Release name on GitHub is prefixed.

**Comment by nicwortel** [comment]
The release / version should never contain a prefix. The prefix is only used for the Git tag. If I recall correctly the [releases for this tool](https://github.com/leviy/release-tool/releases) have been created with calculated version numbers, so I cannot seem to reproduce this.

Can you show an example where a GitHub release is created with a "v" prefix?

**Comment by BasMatthee** [comment]
After a second look at our releases I noticed that not all releases were done using the release-tool. Resulting in hand-work where my colleagues prefixed the release title with the `v`.

In short. This 'issue' can be closed not being an issue.
